apps/news/urls.py
# -*- coding: utf-8 -*-
from django.urls import path
from . import views
app_name = 'news'

urlpatterns = [
    path('<int:news_id>/', views.news_detail,name='news_detail'),
    path('list/', views.new_list,name='new_list'),
    path('public_comment/', views.public_comment,name='public_comment'),
]

xfz/urls.py
from django.urls import path,include
from apps.news import views
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('',views.index,name='index'),
    # path('search/',include('haystack.urls')),
    path('search/',views.search,name='search'),
    path('cms/',include('apps.cms.urls')),
    path('account/',include('apps.xfzauth.urls')),
    path('news/', include('apps.news.urls')),
    path('course/', include('apps.course.urls')),
    path('payinfo/', include('apps.payinfo.urls')),
    path('ueditor/', include('apps.ueditor.urls')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(path("__debug__/",include(debug_toolbar.urls)))

apps/news/models.py
from django.db import models

# Create your models here.
class NewsCategory(models.Model):
    name = models.CharField(max_length=20)


class News(models.Model):
    title = models.CharField(max_length=200)
    desc = models.CharField(max_length=200)
    thumbnail = models.URLField()
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    category = models.ForeignKey('NewsCategory', on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey('xfzauth.User', on_delete=models.SET_NULL, null=True)
    class Meta:
        ordering = ['-pub_time']

class Comment(models.Model):
    content = models.TextField()
    pub_time = models.DateTimeField(auto_now_add=True)
    news = models.ForeignKey("News",on_delete=models.CASCADE,related_name='comments')
    author = models.ForeignKey("xfzauth.User",on_delete=models.CASCADE)
    class Meta:
        ordering = ['-pub_time']


class Banner(models.Model):
    priority = models.IntegerField(default=0)
    image_url = models.URLField()
    link_to = models.URLField()
    pub_time = models.DateTimeField(auto_now_add=True)
    class Meta:
        ordering = ['-priority']

apps/news/forms.py
# -*- coding: utf-8 -*-
from django import forms
from apps.forms import FormMixin

class PublicCommentForm(forms.Form, FormMixin):
    content = forms.CharField()
    news_id = forms.IntegerField()

apps/news/views.py
from django.shortcuts import render
from .models import NewsCategory,News,Comment,Banner
from django.conf import settings
from .serializers import NewSerializer,CommentSerizlizer
from utils import restful
from django.http import Http404
from .forms import PublicCommentForm
from apps.xfzauth.decorators import xfz_login_required
from django.db.models import Q
# Create your views here.

def index(request):
    count = settings.ONE_PAGE_NEWS_COUNT
    categorys = NewsCategory.objects.all()
    news = News.objects.select_related('category','author')[0:count]
    context = {
        'categorys':categorys,
        'news':news,
        'banners':Banner.objects.all()
    }
    return render(request,'news/index.html',context=context)

#处理新闻列表
def new_list(request):
    #默认是从第一页开始
    # 通过p参数，来指定要获取第几页的数据
    # 并且这个p参数，是通过查询字符串的方式传过来的/news/list/?p=2
    page = int(request.GET.get('p',1))
    #category_id=0是不进行任何分类
    category_id = int(request.GET.get('category_id',0))
    #计算起始和结束的值
    start = (page-1)*settings.ONE_PAGE_NEWS_COUNT
    end = start+settings.ONE_PAGE_NEWS_COUNT
    # {'id':1,'title':'abc',category:{"id":1,'name':'热点'}}
    if category_id==0:
        newses = News.objects.select_related('category','author').all()[start:end]
    else:
        newses = News.objects.select_related('category','author').filter(category_id=category_id)[start:end]
        #下面的many是代表很多都需要序列化
    serializer = NewSerializer(newses,many=True)
    data = serializer.data
    return restful.result(data=data)
def news_detail(request,news_id):
    try:
        #prefetch_related('comments__author')会执行俩次请求，首先是查找comments然后找到comments的author，执行俩次操作
        news = News.objects.select_related('category','author').prefetch_related('comments__author').get(pk=news_id)
        context = {
            'news':news,
        }
        return render(request,'news/news_detail.html',context=context)
    except News.DoesNotExist:
        raise Http404

@xfz_login_required
def public_comment(request):
    form = PublicCommentForm(request.POST)
    if form.is_valid():
        news_id = form.cleaned_data.get('news_id')
        content = form.cleaned_data.get('content')
        news = News.objects.get(pk=news_id)
        comment = Comment.objects.create(content=content,news=news,author=request.user)
        serizlize = CommentSerizlizer(comment)
        return restful.result(data=serizlize.data)
    else:
        return restful.params_error(message=form.get_errors())
def search(request):
    con = request.GET.get('q')
    context = {}
    if con:
        newses = News.objects.filter(Q(title__icontains=con)|Q(desc__icontains=con))
        context['newses'] = newses
        # print("=================")
    return render(request,'search/search1.html',context=context)

front/templates/news/index.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title %}
    小饭桌
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/index.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/index.min.js' %}"></script>
    <script id="news_item" type="text/plain">
        {% verbatim %}
            {{ each newses news index }}
                <li>
                    <div class="thumbnail-group">
                        <a href="/news/{{ news.id }}/">
                            <img src="{{ news.thumbnail }}" alt="">
                        </a>
                    </div>
                    <div class="news-group">
                        <p class="title">
                            <a href="/news/{{ news.id }}/">{{ news.title }}</a>
                        </p>
                        <p class="desc">
                            {{ news.desc }}
                        </p>
                        <p class="more">
                            <span class="category">
                                {{ news.category.name }}
                            </span>
                            <span class="put-time">{{ news.pub_time|timeSince }}</span>
                            <span class="author">{{ news.author.username }}</span>
                        </p>
                    </div>
                </li>
            {{ /each }}
        {% endverbatim %}
    </script>
{% endblock %}
{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="banner-group" id="banner-group">
                    <ul class="banner-ul" id="banner-ul">
                        {% for banner in banners %}
                            <li>
                                <a href="{{ banner.link_to }}">
                                    <img src="{{ banner.image_url }}" alt="">
                                </a>
                            </li>
                        {% endfor %}
                    </ul>
                    <span class="arrow left-arrow">‹</span>
                    <span class="arrow right-arrow">›</span>
                    <div class="page-control-group">
                        <ul class="page-control">

                        </ul>
                    </div>
                </div>
                <div class="list-outer-group">
                    <ul class="list-tab">
                        <li class="active" data-category="0"><a href="#">最新资讯</a></li>
                        {% for category in categorys %}
                               <li data-category="{{ category.id }}"><a href="#">{{ category.name }}</a></li>
                        {% endfor %}
                    </ul>
                    <ul class="list-inner-group">
                        {% for news in news %}
                             <li>
                                <div class="thumbnail-group">
                                    <a href="{% url 'news:news_detail' news_id=news.id %}">
                                        <img src="{{ news.thumbnail }}" alt="">
                                    </a>
                                </div>
                                <div class="news-group">
                                    <p class="title">
                                        <a href="{% url 'news:news_detail' news_id=news.id %}">{{ news.title }}</a>
                                    </p>
                                    <p class="desc">
                                        {{ news.desc }}
                                    </p>
                                    <p class="more">
                                        <span class="category">
                                            {{ news.category.name }}
                                        </span>
                                        <span class="put-time">{{ news.pub_time|time_since }}</span>
                                        <span class="author">{{ news.author.username }}</span>
                                    </p>
                                </div>
                            </li>
                        {% endfor %}

                    </ul>
                    <div class="load-more-group">
                        <button class="load-more" id="load-more-btn">
                            查看更多
                        </button>
                    </div>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}

front/templates/news/news_detail.html
{% extends 'base/front_base.html' %}
{% load news_filters %}
{% block title %}
    新闻详情
{% endblock %}
{% block head %}
    <link rel="stylesheet" href="{% static 'css/news/news_detail.min.css' %}">
    <script src="{% static 'arttemplate/template-web.js' %}"></script>
    <script src="{% static 'js/news_detail.min.js' %}"></script>
    <script id="comment-item" type="text/html">
    {% verbatim %}
        <li>
            <div class="comment-info">
                <img src="https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1528129845916&di=536993042d5223862f8c4ab157ba6e72&imgtype=0&src=http%3A%2F%2Fpic1.ipadown.com%2Fimgs%2F201206120933354195.jpg" alt="" class="avatar">
                <span class="author">{{ comment.author.username }}</span>
                <span class="pub-time">{{ comment.pub_time|timeSince }}</span>
            </div>
            <p class="comment-content">{{ comment.content }}</p>
        </li>
    {% endverbatim %}
    </script>
{% endblock %}
{% block main %}
    <div class="main">
        <div class="wrapper">
            <div class="main-content-wrapper">
                <div class="news-wrapper">
                    <h1 class="title">{{ news.title }}</h1>
                    <div class="news-info">
                        <div class="info-group">
                            <span class="author">{{ news.author.username }}</span>
                            <span class="pub-time">{{ news.pub_time|time_since }}</span>
                            <span class="category">{{ news.category.name }}</span>
                        </div>
                        <div class="share-group">
                            <span>分享至：</span>
                            <a class="weixin share-item"></a>
                            <a href="#" class="weibo share-item"></a>
                        </div>
                    </div>
                    <article class="article">
                        {{ news.content|safe }}
                    </article>
                </div>
                <div class="comment-wrapper">
                    <h3 class="title">文章评论（0）</h3>
                    <textarea name="comment" class="comment-textarea logined-textarea" placeholder="立即登录，参与评论~"></textarea>
                    <div class="submit-btn-group">
                        <button data-news-id="{{ news.pk }}" class="submit-btn">立即评论</button>
                    </div>
                    <ul class="comment-list">
                       {% for comment in news.comments.all %}
                            <li>
                                <div class="comment-info">
                                    <img src="{% static 'images/1548041289_416.jpg' %}" alt="" class="avatar">
                                    <span class="author">{{ comment.author.username }}</span>
                                    <span class="pub-time">{{ comment.pub_time|time_since }}</span>
                                </div>
                                <p class="comment-content">{{ comment.content }}</p>
                            </li>
                       {% endfor %}
                    </ul>
                </div>
            </div>
            {% include 'common/sidebar.html' %}
        </div>
    </div>
{% endblock %}